default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: codio
  password:
  host: localhost

development:
  <<: *default
  database: rottenpotatoes_development

test:
  <<: *default
  database: rottenpotatoes_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>


